# https://github.com/andreashuber69/lightning-node-operator/blob/develop/README.md
os: linux
dist: focal
language: node_js
node_js:
- lts/*

branches:
  only:
  - develop
  - /^release\/.*/
  - master

script:
- npm run ci

after_script:
- npx coveralls <./coverage/lcov.info

deploy:
  provider: npm
  cleanup: false
  email:
    secure: "GuyemP7gxSd8cSK9oj/HeU1PGF6+HNwvPxnqjsCxqUi+S0sm9i0ksjKwFMRCbyomvJmCISU2QoDUTh1WlArVgiQjk7SORMmgV8tBC2jgsP5yUBjbTk3H2hCMWRwnl7jYytlS+GseMKjtuHJ7dRQ8FG3oCnFgegpkj/E1B9lAxgwvuyFsmHXAKWjAX0calvRB+uFMfmlOlyEWoZcLwUtiNyJY0DdrDW6pQsAqk0Rwtb7xf5HpBiv8HOzNFD+vPaDbXVzclgBx0ooNj0epywOiDY1vac1iDCjOVxgyXKS513nyHlDPJDA5lBFckVnfbGM3NRDOyJxyjcqHPTkLgyD+VJk0MY0849GaGYZGBv/3fA60WVd8dsD3H8patts1mFD8SGVGB+OgrPtRmInoJjB2/5s1DoPp98snLxV0pSctK2/+wYr0Q0PLOV2ejSwJEmURi0f2sBcZJZ+JqvH9bYYUerG3tyzsyunuzPQ0t75JATw3+WAi5nH6DSBXURD9zi9I4Jq2oOq8R96Ktk7ObfGSWwWMiolaIWoO9Ukka1W8aYkrfgazDtkIsaBGZ6znE8nSxwpKan0zChrHhGxfDrrnjBF8/ap2Osi0s1bFwk9KoN9mt68S2cgLxxXY453wockwF/GU6TDkP96nT20DAOHtViogpYLg4Ffg+74t0A7aaJQ="
  api_token:
    secure: "jj3ovE52VIgfZImN8kSN0GmtplOSlLhqp5ytiAftRw9c1RDNPIAgKCW3VZSx1NfvNGzlgbmqBNXCFdFTlW+mqYy3kVNDL3wdcqIayqWOG6z3L85jwSKzH4aFkkhheFFi5nHoGIK7t8QlJ2bveKWK6nyf5sN2ULSZc4WfhQGhZOt8jo4cV5+t+SLZSKxX8DxF/7M0ZCtzmMfjgq/gxDLFO7nQYWLiBDcCversvh0ic0Vv8iZTrUTVk+1gi1P+DcsBECddu15z/zLctGW52u3MwBhbYD73yeuCnqW6nhk+Kg8TLJ+fRKybudo1IdBg4KljqxmFX4hW5wiuy14VDMiTCBAbl+lydaqE5ErWS4a+uyhnu2Ti5OLNJPOrFbKyzKO9G/2ZbNO0j42qFlwEADQJSil4g1mb27JuIj3B/zSEsGr/4OJ57ME5Ipsxt12BEpIP5mc2kTM/KHXhFMWCw9yE4KNhyzN9NPvZMr1OXV/RyZZWZ4cUeKuHnhJV2PkSeIjSgzRA83+DiioX1fQjlUeyncYhPlOlrx4L5h93SvxwzoUuKWeCJ+OZUViAVT9UsFWag0j5Mu6lvjBtsiqRV0zVYtuMngq1A+6Do8OzDxHFmJIhk2KT7j00WgCg71MKCkZ0EJ804MP7Y5LZX7PxVWHb2Dk+SswGVSMILM5UscWjBOA="
  on:
    branch: master

notifications:
  email:
    recipients:
    - secure: "zdx7CC1COf0BXWHk5meDM8UFQyGK9kRXOMC1FVS+xFdHu/Xf5oehkMHzdCGzWc9xKtHnjRGuNj7wRFyc26EG60E6YXyWXPSruZO1SjisO0YmLpbSLxrUgQoph/yTdoScMkx46z0g91w/IZKh0PL5mXUE+i77tqQHUPPtjXNmN9W22R8IUdYGy1n7oMZqNXwYB8ty8owuBg1BvEiJumg67gI5v7SRYiubMsVq5weYCftlIoS3+mYFCvxPS9k+GsYp6XZKs1fIroNvKoLiJwCEfup4Q6ibDYR+P8whSMgNq125NcIOyEqjT+UP68vndCoZEXE+p+az6bmF4EWDN9dqSLqYel2uJJ2EOnPu4twqhNemd6qWR9pBvPk1QuTgt7NMrElhQklgi6BbKuUFuWhbm+8n8LI2/BrHJF+iUq1ZOi9Gr88b5JPG0bX2FEWEbCp5wd3ckGuCU/hOWqBfZQ45Qs7qHyMn8xCjluB6t7Q8OOawXiqkENhcCvnKYX0nv4zRSXS2v2KOyAi6s6zKziy0Ac6qXynxU5SuzDLu8pWCqkphbFGoWij+S6+bClMjOvc+6BLYBG95hDW0VZfb86pgqeGvCYiWO3xOhDhd+Pcnx4gr1flO1EfcsMSaMu3cGJmbcRbNxxISgyZqdmvhn/OGf4aWM6zNZyuf7IsaTP+il0g="
